### ISSUE TITLE
没太明白框架的作用

### ISSUE THREAD

**Issue by HuRuWo** [AndroidPureLand/AutoTest#2]
我的理解好像是把所有的接口跑一遍
然后是验证结果吗
类似有前后关系的接口如何验证，比如:
访问接口A得到结果后，拿A的结果去访问B接口如何验证

**Comment by 80945540** [comment]
先预设好参数嘛  就是验证每个接口是否都通  以及结果是否正确 请求时间是否在预设的范围内   因为很多打点的公司是集群服务器 发布到正式后 可能会出现部分服务器有没成功等诸多问题
